run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/romel/go-database

issues:
  exclude-rules:
    # Ignore test files for some linters
    - path: _test\.go
      linters:
        - unused
    # Ignore testutils for some linters  
    - path: test/utils/
      linters:
        - unused
    # Allow log.Fatal in main
    - path: cmd/
      linters:
        - gocritic